<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServomotorColumnPropertiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('servomotor_properties')->insert([
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Mierna',
                'code' => '1',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-25°C ... +55°C',
                'code' => '1',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C3',
                'code' => '1',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 67',
                'code' => '1',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Mierna',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-25°C ... +55°C',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C3',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 68',
                'code' => '5',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Tropická vlhká + ČOV',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-25°C ... +55°C',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C4',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 67',
                'code' => '5',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Chladná',
                'code' => '3',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-50°C ... +40°C',
                'code' => '3',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C3',
                'code' => '3',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 67',
                'code' => '3',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Tropická suchá a suchá',
                'code' => '6',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-25°C ... +55°C',
                'code' => '6',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C3',
                'code' => '6',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 67',
                'code' => '6',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Morská',
                'code' => '7',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-50°C ... +40°C',
                'code' => '7',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C4',
                'code' => '7',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 67',
                'code' => '7',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 1,
                'price' => 5,
                'text' => 'Arktická',
                'code' => '8',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 2,
                'price' => 5,
                'text' => '-60°C ... +40°C',
                'code' => '8',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 3,
                'price' => 5,
                'text' => 'C3',
                'code' => '8',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 4,
                'price' => 5,
                'text' => 'IP 67',
                'code' => '8',
            ],
        ]);
        //
        DB::table('servomotor_properties')->insert([
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 5,
                'price' => 5,
                'text' => 'Na svorkovnicu',
                'code' => '0',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 6,
                'price' => 5,
                'text' => '230 V AC',
                'code' => '0',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 7,
                'price' => 5,
                'text' => 'Z1a + Z11a ',
                'code' => '0',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 5,
                'price' => 5,
                'text' => 'Na svorkovnicu',
                'code' => 'L',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 6,
                'price' => 5,
                'text' => '220 V AC',
                'code' => 'L',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 7,
                'price' => 5,
                'text' => 'Z1a + Z11a ',
                'code' => 'L',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 5,
                'price' => 5,
                'text' => 'Na svorkovnicu',
                'code' => '9',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 6,
                'price' => 5,
                'text' => '3x400 V AC',
                'code' => '9',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 7,
                'price' => 5,
                'text' => 'Z78a + Z12a',
                'code' => '9',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 5,
                'price' => 5,
                'text' => 'Na konektor',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 6,
                'price' => 5,
                'text' => '230 V AC',
                'code' => '5',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 7,
                'price' => 5,
                'text' => 'Z1a + Z11a',
                'code' => '5',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 5,
                'price' => 5,
                'text' => 'Na konektor',
                'code' => '7',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 6,
                'price' => 5,
                'text' => '3x400 V AC',
                'code' => '7',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 7,
                'price' => 5,
                'text' => 'Z78a + Z12a',
                'code' => '7',
            ],
        ]);
        //
        DB::table('servomotor_properties')->insert([
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                         'servomotor_property_column_id' => 8,
                        'price' => 5,
                        'text' => '46 Nm',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 9,
                        'price' => 5,
                        'text' => '40 Nm',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 10,
                        'price' => 5,
                        'text' => '-',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                         'servomotor_property_column_id' => 11,
                        'price' => 5,
                        'text' => '10 s/90°',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 12,
                        'price' => 5,
                        'text' => '15',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 6,
                        'servomotor_property_column_id' => 13,
                        'price' => 5,
                        'text' => '10 s/90°',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 7,
                         'servomotor_property_column_id' => 28,
                        'price' => 5,
                        'text' => '15',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 8,
                        'servomotor_property_column_id' => 29,
                        'price' => 5,
                        'text' => '20',
                        'code' => '0',
                    ],
                    //
                                        [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                         'servomotor_property_column_id' => 8,
                        'price' => 5,
                        'text' => '46 Nm',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 9,
                        'price' => 5,
                        'text' => '40 Nm',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 10,
                        'price' => 5,
                        'text' => '-',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                         'servomotor_property_column_id' => 11,
                        'price' => 5,
                        'text' => '10 s/90°',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 12,
                        'price' => 5,
                        'text' => '15',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 6,
                        'servomotor_property_column_id' => 13,
                        'price' => 5,
                        'text' => '10 s/90°',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 7,
                         'servomotor_property_column_id' => 28,
                        'price' => 5,
                        'text' => '15',
                        'code' => '0',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 8,
                        'servomotor_property_column_id' => 29,
                        'price' => 5,
                        'text' => '20',
                        'code' => '0',
                    ],
                    //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                         'servomotor_property_column_id' => 8,
                        'price' => 5,
                        'text' => '90 Nm',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 9,
                        'price' => 5,
                        'text' => '80 Nm',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 10,
                        'price' => 5,
                        'text' => '63 Nm',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                         'servomotor_property_column_id' => 11,
                        'price' => 5,
                        'text' => '20 s/90°',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 12,
                        'price' => 5,
                        'text' => '15',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 6,
                        'servomotor_property_column_id' => 13,
                        'price' => 5,
                        'text' => '20 s/90°',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 7,
                         'servomotor_property_column_id' => 28,
                        'price' => 5,
                        'text' => '15',
                        'code' => '1',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 8,
                        'servomotor_property_column_id' => 29,
                        'price' => 5,
                        'text' => '20',
                        'code' => '1',
                    ],
                    //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                         'servomotor_property_column_id' => 8,
                        'price' => 5,
                        'text' => '90 Nm',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 9,
                        'price' => 5,
                        'text' => '80 Nm',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 10,
                        'price' => 5,
                        'text' => '63 Nm',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                         'servomotor_property_column_id' => 11,
                        'price' => 5,
                        'text' => '40 s/90°',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 12,
                        'price' => 5,
                        'text' => '15',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 6,
                        'servomotor_property_column_id' => 13,
                        'price' => 5,
                        'text' => '40 s/90°',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 7,
                         'servomotor_property_column_id' => 28,
                        'price' => 5,
                        'text' => '15',
                        'code' => '2',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 8,
                        'servomotor_property_column_id' => 29,
                        'price' => 5,
                        'text' => '20',
                        'code' => '2',
                    ],
                    //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                         'servomotor_property_column_id' => 8,
                        'price' => 5,
                        'text' => '72 Nm',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 9,
                        'price' => 5,
                        'text' => '63 Nm',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 10,
                        'price' => 5,
                        'text' => '50 Nm',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                         'servomotor_property_column_id' => 11,
                        'price' => 5,
                        'text' => '80 s/90°',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 12,
                        'price' => 5,
                        'text' => '4',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 6,
                        'servomotor_property_column_id' => 13,
                        'price' => 5,
                        'text' => '-',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 7,
                         'servomotor_property_column_id' => 28,
                        'price' => 5,
                        'text' => '-',
                        'code' => '3',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 8,
                        'servomotor_property_column_id' => 29,
                        'price' => 5,
                        'text' => '-',
                        'code' => '3',
                    ],
                    //
                ]);
        //
        DB::table('servomotor_properties')->insert([
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'S pevnými dorazmi 60°',
                        'code' => 'A',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'S pevnými dorazmi 90°',
                        'code' => 'B',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'S pevnými dorazmi 120°',
                        'code' => 'C',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'S pevnými dorazmi 160°',
                        'code' => 'D',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'Bez dorazov 60°',
                        'code' => 'K',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'Bez dorazov 90°',
                        'code' => 'L',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'Bez dorazov 120°',
                        'code' => 'M',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'Bez dorazov 160°',
                        'code' => 'N',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'Bez dorazov 360°',
                        'code' => 'P',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 14,
                        'price' => 5,
                        'text' => 'Bez dorazov > 0°£ 360°',
                        'code' => 'Z',
                    ],
                ]);
        //
        DB::table('servomotor_properties')->insert([
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                'servomotor_property_column_id' => 15,
                'price' => 5,
                'text' => 'Bez vysielača',
                'code' => 'A',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 16,
                'price' => 5,
                'text' => '-',
                'code' => 'A',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 17,
                'price' => 5,
                'text' => '-',
                'code' => 'A',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 18,
                'price' => 5,
                'text' => '-',
                'code' => 'A',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 15,
                'price' => 5,
                'text' => 'Odporový jednoduchý',
                'code' => 'B',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 16,
                'price' => 5,
                'text' => '-',
                'code' => 'B',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 17,
                'price' => 5,
                'text' => '1 x 100 W',
                'code' => 'B',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 18,
                'price' => 5,
                'text' => 'Z5a',
                'code' => 'B',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 15,
                'price' => 5,
                'text' => 'Odporový jednoduchý',
                'code' => 'F',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 16,
                'price' => 5,
                'text' => '-',
                'code' => 'F',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 17,
                'price' => 5,
                'text' => '1 x 2 000  W',
                'code' => 'F',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 18,
                'price' => 5,
                'text' => 'Z5a',
                'code' => 'F',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 15,
                'price' => 5,
                'text' => 'Odporový Dvojitý',
                'code' => 'K',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 16,
                'price' => 5,
                'text' => '-',
                'code' => 'K',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 17,
                'price' => 5,
                'text' => '2 x 100 W',
                'code' => 'K',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 18,
                'price' => 5,
                'text' => 'Z6a',
                'code' => 'K',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 15,
                'price' => 5,
                'text' => 'Odporový Dvojitý',
                'code' => 'P',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 16,
                'price' => 5,
                'text' => '-',
                'code' => 'P',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 17,
                'price' => 5,
                'text' => '2 x 2 000 W',
                'code' => 'P',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 18,
                'price' => 5,
                'text' => 'Z6a',
                'code' => 'P',
            ],
            //
            [
                'servomotor_id' => 1,
                'row_id' => 1,
                 'servomotor_property_column_id' => 15,
                'price' => 5,
                'text' => 'Elektronický - prúdový / Bez zdroja',
                'code' => 'S',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 2,
                'servomotor_property_column_id' => 16,
                'price' => 5,
                'text' => '2-vodič',
                'code' => 'S',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 3,
                'servomotor_property_column_id' => 17,
                'price' => 5,
                'text' => '4 - 20 mA',
                'code' => 'S',
            ],
            [
                'servomotor_id' => 1,
                'row_id' => 4,
                'servomotor_property_column_id' => 18,
                'price' => 5,
                'text' => 'Z10a',
                'code' => 'S',
            ],
        ]);
        //
        DB::table('servomotor_properties')->insert([
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 19,
                        'price' => 5,
                        'text' => 'Príruba, ISO 5211, F05/F07',
                        'code' => 'A',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 20,
                        'price' => 5,
                        'text' => 'D-14',
                        'code' => 'A',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 21,
                        'price' => 5,
                        'text' => '14x14',
                        'code' => 'A',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 22,
                        'price' => 5,
                        'text' => 'P-1147, P-2148/A',
                        'code' => 'A',
                    ],
                    //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 19,
                        'price' => 5,
                        'text' => 'Príruba, ISO 5211, F05/F07',
                        'code' => 'B',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 20,
                        'price' => 5,
                        'text' => 'L-14',
                        'code' => 'B',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 21,
                        'price' => 5,
                        'text' => '14x14',
                        'code' => 'B',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 22,
                        'price' => 5,
                        'text' => 'P-1147, P-2148/A',
                        'code' => 'B',
                    ],
                    //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 19,
                        'price' => 5,
                        'text' => 'Stojan, výstupný hriadeľ, pero',
                        'code' => 'J',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 20,
                        'price' => 5,
                        'text' => '-',
                        'code' => 'J',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 21,
                        'price' => 5,
                        'text' => 'Ø22',
                        'code' => 'J',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 22,
                        'price' => 5,
                        'text' => 'P-1162, P-0210, P-2148/A',
                        'code' => 'J',
                    ],
                     //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 19,
                        'price' => 5,
                        'text' => 'Stojan + Páka + Ťahadlo TV 360',
                        'code' => 'L',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 20,
                        'price' => 5,
                        'text' => '-',
                        'code' => 'L',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 21,
                        'price' => 5,
                        'text' => '-',
                        'code' => 'L',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 22,
                        'price' => 5,
                        'text' => 'P-1162, P-0210, P-2148/A',
                        'code' => 'L',
                    ],
                ]);
                DB::table('servomotor_properties')->insert([
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 23,
                        'price' => 5,
                        'text' => '2 prídavné polohové spínače',
                        'code' => '00',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 24,
                        'price' => 5,
                        'text' => 'Z11a',
                        'code' => '00',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 25,
                        'price' => 5,
                        'text' => 'Z12a',
                        'code' => '00',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 26,
                        'price' => 5,
                        'text' => 'Z507',
                        'code' => '00',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 6,
                        'servomotor_property_column_id' => 27,
                        'price' => 5,
                        'text' => 'Z503',
                        'code' => '00',
                    ],
                    //
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 23,
                        'price' => 5,
                        'text' => 'Vyhrievací odpor s tepelným spínačom ',
                        'code' => '02',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 24,
                        'price' => 5,
                        'text' => 'Z1a',
                        'code' => '02',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 25,
                        'price' => 5,
                        'text' => 'Z78a',
                        'code' => '02',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 26,
                        'price' => 5,
                        'text' => 'Z507',
                        'code' => '02',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 27,
                        'price' => 6,
                        'text' => 'Z503',
                        'code' => '02',
                    ],
                    // 
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 23,
                        'price' => 5,
                        'text' => 'Miestne ovládanie (len do -40 °C)',
                        'code' => '07',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 24,
                        'price' => 5,
                        'text' => 'Z270i',
                        'code' => '07',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 25,
                        'price' => 5,
                        'text' => 'Z90c',
                        'code' => '07',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 26,
                        'price' => 5,
                        'text' => 'Z509b',
                        'code' => '07',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 27,
                        'price' => 6,
                        'text' => 'Z505b',
                        'code' => '07',
                    ],
                    // 
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 23,
                        'price' => 5,
                        'text' => 'Vyhrievací odpor',
                        'code' => '15',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 24,
                        'price' => 5,
                        'text' => 'Z1a',
                        'code' => '15',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 25,
                        'price' => 5,
                        'text' => 'Z78a',
                        'code' => '15',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 26,
                        'price' => 5,
                        'text' => 'Z507',
                        'code' => '15',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 27,
                        'price' => 6,
                        'text' => 'Z503',
                        'code' => '15',
                    ],
                    // 
                    [
                        'servomotor_id' => 1,
                        'row_id' => 1,
                        'servomotor_property_column_id' => 23,
                        'price' => 5,
                        'text' => 'Pozlátené kontakty mikrospínačov, detaily po konzultácii s výrobcom ',
                        'code' => '40',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 2,
                        'servomotor_property_column_id' => 24,
                        'price' => 5,
                        'text' => '-',
                        'code' => '40',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 3,
                        'servomotor_property_column_id' => 25,
                        'price' => 5,
                        'text' => '-',
                        'code' => '40',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 4,
                        'servomotor_property_column_id' => 26,
                        'price' => 5,
                        'text' => '-',
                        'code' => '40',
                    ],
                    [
                        'servomotor_id' => 1,
                        'row_id' => 5,
                        'servomotor_property_column_id' => 27,
                        'price' => 6,
                        'text' => '-',
                        'code' => '40',
                    ],
                ]);
    }
}
